        const quotes = [
            "The only way to do great work is to love what you do. ~ Steve Jobs",
            "Life is what happens when you’re busy making other plans. ~ John Lennon",
            "In the end, it’s not the years in your life that count. It’s the life in your years. ~ Abraham Lincoln",
            "Believe you can and you’re halfway there. ~ Theodore Roosevelt",
            "The future belongs to those who believe in the beauty of their dreams. ~ Eleanor Roosevelt",
            "Success is not final, failure is not fatal: It is the courage to continue that counts. ~ Winston Churchill",
            "You miss 100% of the shots you don’t take. ~ Wayne Gretzky",
            "Do not watch the clock. Do what it does. Keep going. ~ Sam Levenson",
            "The only limit to our realization of tomorrow is our doubts of today. ~ Franklin D. Roosevelt",
            "It always seems impossible until it’s done. ~ Nelson Mandela",
            "The only true wisdom is in knowing you know nothing. ~ Socrates",
            "We are what we repeatedly do. Excellence, then, is not an act, but a habit. ~ Aristotle",
            "Happiness depends upon ourselves. ~ Aristotle",
            "The unexamined life is not worth living. ~ Socrates",
            "To live is the rarest thing in the world. Most people exist, that is all. ~ Oscar Wilde",
            "Be the change that you wish to see in the world. ~ Mahatma Gandhi",
            "Life is really simple, but we insist on making it complicated. ~ Confucius",
            "The mind is everything. What you think, you become. ~ Buddha",
            "Knowing yourself is the beginning of all wisdom. ~ Aristotle",
            "The greatest glory in living lies not in never falling, but in rising every time we fall. ~ Nelson Mandela",
            "Why do we fall? So we can learn to pick ourselves up. ~ The Dark Knight Rises",
            "No one can make you feel inferior without your consent. ~ The Help",
            "Life moves pretty fast. If you don’t stop and look around once in a while, you could miss it. ~ Ferris Bueller’s Day Off",
            "If you can’t avoid suffering, then make it meaningful. ~ My Mister",
            "The moment you want to give up, think of the reason why you held on for so long. ~ Start-Up",
            "A wound that’s never revealed can never heal. ~ Descendants of the Sun",
            "Pain is inevitable. Suffering is optional. ~ It’s Okay to Not Be Okay",
            "It’s not the fear of failure that stops you… It’s the fear of looking stupid. ~ BoJack Horseman",
            "If you’re always scared of losing, you’ve already lost. ~ Arya Stark, Game of Thrones",
            "No amount of anxiety makes any difference to anything that’s going to happen. ~ Alan Watts",
            "Courage is not the absence of fear, but the triumph over it. ~ Nelson Mandela",
            "In the end, we only regret the chances we didn’t take. ~ Lewis Carroll",
            "Never let your pride keep you from doing what you know is right. ~ Samwise Gamgee, The Lord of the Rings",
            "The chains of habit are too light to be felt until they’re too heavy to be broken. ~ Warren Buffett",
            "We suffer more often in imagination than in reality. ~ Seneca",
            "Twenty years from now, you’ll be more disappointed by the things you didn’t do than by the ones you did. ~ Mark Twain",
            "Pride is not the opposite of shame, but its source. ~ Iroh, Avatar: The Last Airbender",
            "The ego is the enemy of what you say you want. ~ Ryan Holiday",
            "Swallow your pride occasionally. It’s non-fattening. ~ Frank Clark",
            "A man’s pride can be his downfall, and he needs to learn when to turn to others for support. ~ Dumbledore, Harry Potter",
            "The moment you feel shame for needing help is the moment your ego is lying to you. ~ Unknown",
            "You can’t cling to the past because no matter how tightly you hold on, it’s already gone. ~ Ted Lasso",
            "The trouble is, you think you have time. ~ Buddha",
            "Discipline is choosing between what you want now and what you want most. ~ Abraham Lincoln",
            "The only thing standing between you and your goal is the bullshit story you keep telling yourself. ~ Jordan Belfort",
            "Your life doesn’t get better by chance. It gets better by change. ~ Jim Rohn",
            "Burn the boats. If you want to take the island, burn the boats. ~ Tony Robbins",
            "It’s easy to forget what a sin is in the middle of a battlefield. ~ Metal Gear Solid",
            "A loser isn’t someone who gets knocked down. It’s someone who stays down. ~ Rocky Balboa",
            "Failure is the best teacher. But life doesn’t give you a second chance. I do. ~ Kakashi, Naruto",
            "If you don’t take risks, you can’t create a future. ~ Monkey D. Luffy, One Piece",
            "The moment you give up is the moment you let someone else win. ~ Kanye West",
            "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better. ~ Samuel Beckett",
            "The worst kind of pain is when you’re smiling just to stop the tears from falling. ~ Attack on Titan",
            "It’s okay to lose. It’s not okay to fear losing. ~ Levi, Attack on Titan",
            "Sometimes you must hurt in order to know, fall in order to grow, lose in order to gain. ~ Pain, Naruto",
            "A man who can’t endure shame can’t be trusted with glory. ~ Game of Thrones",
            "The only shame is in giving up. ~ Guts, Berserk",
            "Fear is a tool. The devil whispered to me, ‘You’re not strong enough to withstand the storm.’ I whispered back, ‘I am the storm.’ ~ Anonymous",
            "The past can hurt. But the way I see it, you can either run from it or learn from it. ~ Lion King",
            "Time doesn’t heal wounds. It just teaches you how to live with them. ~ Vinland Saga",
            "You can’t change the past, but you can let it go. ~ Ragnar Lothbrok, Vikings",
            "What’s done is done. What’s gone is gone. One of life’s lessons is always moving on. ~ Cowboy Bebop",
            "The only time you should look back is to see how far you’ve come. ~ BTS",
            "Destiny is not a matter of chance. It’s a matter of choice. ~ William Jennings Bryan",
            "A man’s dream will never die! ~ Blackbeard, One Piece",
            "You were born with wings. Why prefer to crawl through life? ~ Rumi",
            "Knowing you’re different is only the beginning. Accepting it is the next step. Embracing it is beyond courage. ~ Edward Elric, Fullmetal Alchemist",
            "If you don’t like your destiny, don’t accept it. Instead, have the courage to change it. ~ Naruto Uzumaki",
            "The hardest choices require the strongest wills. ~ Thanos, Avengers",
            "When you’re at the bottom, the only way left is up. ~ Tokyo Revengers",
            "People’s lives don’t end when they die. It ends when they lose faith. ~ Itachi, Naruto",
            "Hell is other people. ~ Jean-Paul Sartre",
            "Surpass your limits. Right here, right now! ~ Goku, Dragon Ball",
            "Wake up to reality. Nothing ever goes as planned in this world. ~ Madara Uchiha, Naruto",
            "If you want to be strong, you have to abandon your humanity. ~ Alucard, Hellsing",
            "Don’t pray for an easy life. Pray for the strength to endure a hard one. ~ Bruce Lee",
            "sometimes, you have to be shameless to avoid regret later ~ Unknown",
            "If you hesitate because you’re afraid of looking foolish, you’ll only regret it when it’s too late. ~ Unknown",
            "A sword that has never been sharpened will never cut anything. ~ Unknown",
            "Destiny isn’t something you’re born with—it’s something you seize. ~ Unknown"
        ];
